name: Python Unit Tests
# trigger workflow on push or pull requests
on:
  push:
      branches:
          - master
          - develop
      paths-ignore:
        - 'docs/**'
  pull_request:
      branches:
        - master
        - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install codecov
          pip install coveralls
      - name: Run tests with pytest
        run: python -m coverage run tests/test_all.py || python -m coverage run tests/test_all.py